export default {
  STORY_CHANGE: "STORY_CHANGE",
  STORIES_GET_REQUEST: "STORIES_GET_REQUEST",
  STORIES_GET_SUCCESS: "STORIES_GET_SUCCESS",
  STORIES_GET_FAILURE: "STORIES_GET_FAILURE",
  STORY_UPSERT_REQUEST: "STORY_UPSERT_REQUEST",
  STORY_UPSERT_SUCCESS: "STORY_UPSERT_SUCCESS",
  STORY_UPSERT_FAILURE: "STORY_UPSERT_FAILURE",
  CATEGORIES_GET_REQUEST: "CATEGORIES_GET_REQUEST",
  CATEGORIES_GET_SUCCESS: "CATEGORIES_GET_SUCCESS",
  CATEGORIES_GET_FAILURE: "CATEGORIES_GET_FAILURE",

  //For now we are passing all of our story details in the list, but
  //at some point we should add get calls for a more detailed story
  STORY_SELECT: "STORY_SELECT"

}